<Background>:
    start: start
    options: options
    exit: exit
    MyButton:
        id: start
        pos: root.center_x - self.size[0] / 2, (root.center_y - self.size[1] * 0.5) + self.size[1] * 2
        size: root.width / 5, root.height / 10
        text: "start"
    MyButton:
        id: options
        pos: root.center_x - self.size[0] / 2, (root.center_y - self.size[1] * 0.5)
        size: root.width / 5, root.height / 10
        text: "options"
    MyButton:
        id: exit
        pos: root.center_x - self.size[0] / 2, (root.center_y - self.size[1] * 0.5) - self.size[1] * 2
        size: root.width / 5, root.height / 10
        text: "exit"
